.TH SSHP 1 "October 9, 2026" "General Commands Manual"
.SH NAME

\fBsshp\fR \- Parallel SSH Executor.
.SH SYNOPSIS

\fBsshp [OPTIONS] <command> [arg ...]\fR
.PP
\fBsshp [\-f hosts.txt] [\-g | \-j] <command> [arg ...]\fR
.SH DESCRIPTION

Parallel SSH executor and manager.
.PP
\fBsshp\fR manages multiple ssh processes and handles coalescing their output to
the terminal.  It reads newline\-separated hostnames or IP addresses from
standard input or a file specified with \fB\-f\fR, then starts an ssh subprocess
for each host.  Child stdout and stderr are written to \fBsshp\fR's standard
output.
.SH MODES

\fBsshp\fR has three modes of execution:
.RS
.IP \(bu 2
\fBline mode\fR (line\-by\-line output, default).
.IP \(bu 2
\fBgroup mode\fR (grouped by hostname output, \fB\-g\fR).
.IP \(bu 2
\fBjoin mode\fR (grouped by unique output, \fB\-j\fR).
.RE
.PP
The first two modes, \fBline\fR and \fBgroup\fR, operate in largely the same
way.  They differ only in how data is buffered from the child processes and
printed to the screen.  Line mode buffers the data line\-by\-line, whereas group
mode does no buffering at all and prints the data once it is read from the
child.
.PP
The last mode, \fBjoin\fR, however, buffers \fIall\fP data from all child
processes and produces output once every process has finished.  Instead of
grouping the output by host, it groups identical output and lists the hosts
that produced it.
.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-anonymous\fR
Hide hostname prefix, defaults to \fBfalse\fR\&.
.TP
\fB\-c\fR, \fB\-\-color\fR \fIon|off|auto\fP
Set color output, defaults to \fBauto\fR\&.
.TP
\fB\-d\fR, \fB\-\-debug\fR
Enable debug info, defaults to \fBfalse\fR\&.
.TP
\fB\-e\fR, \fB\-\-exit\-codes\fR
Show command exit codes, defaults to \fBfalse\fR\&.
.TP
\fB\-f\fR, \fB\-\-file\fR \fIfile\fP
A file of hosts separated by newlines, defaults to \fBstdin\fR\&.
.TP
\fB\-g\fR, \fB\-\-group\fR
Group output by hostname (\fBgroup mode\fR).
.TP
\fB\-h\fR, \fB\-\-help\fR
Print this message and exit.
.TP
\fB\-j\fR, \fB\-\-join\fR
Join hosts together by output (\fBjoin mode\fR).  This option is mutually
exclusive with \fB\-a\fR, \fB\-g\fR, and \fB\-s\fR\&.
.TP
\fB\-m\fR, \fB\-\-max\-jobs\fR \fInum\fP
Max processes to run concurrently, defaults to \fB50\fR\&.
.TP
\fB\-n\fR, \fB\-\-dry\-run\fR
Don't actually execute subprocesses.
.TP
\fB\-s\fR, \fB\-\-silent\fR
Silence all output subprocess stdio, defaults to \fBfalse\fR\&.
.TP
\fB\-t\fR, \fB\-\-trim\fR
Trim hostnames (remove domain) on output, defaults to \fBfalse\fR\&.
.TP
\fB\-v\fR, \fB\-\-version\fR
Print the version number and exit.
.TP
\fB\-x\fR, \fB\-\-exec\fR \fIprog\fP
Program to execute, defaults to \fBssh\fR\&.
.TP
\fB\-\-max\-line\-length\fR \fInum\fP
Maximum line length (in \fBline mode\fR only), defaults to \fB1024\fR\&.
.TP
\fB\-\-max\-output\-length\fR \fInum\fP
Maximum output length (in \fBjoin mode\fR only), defaults to \fB8192\fR\&.
.SH SSH OPTIONS

The following options are passed directly to \fBssh\fR:
.TP
\fB\-i\fR, \fB\-\-identity\fR \fIident\fP
ssh identity file to use.
.TP
\fB\-l\fR, \fB\-\-login\fR \fIname\fP
The username to login as.
.TP
\fB\-o\fR, \fB\-\-option\fR \fIkey=val\fP
ssh option passed in key=value form.
.TP
\fB\-p\fR, \fB\-\-port\fR \fIport\fP
The ssh port.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Run ssh in quiet mode.
.SH EXAMPLES

Given the following hosts file called \fBhosts.txt\fR:
.PP
.RS
.nf
# example hosts file
arbiter.rapture.com
cifs.rapture.com
decomp.rapture.com
.fi
.RE
.PP
\fBsshp \-f hosts.txt uname \-v\fR
.IP
Run \fBuname \-v\fR in parallel on hosts supplied by a file.
.PP
\fBsshp \-e exit 0 < hosts.txt\fR
.IP
Parallel ssh into hosts (via \fBstdin\fR) and print the exit codes (\fB\-e\fR).
.PP
\fBsshp \-d id \-un < hosts.txt\fR
.IP
Parallel ssh into hosts and run \fBid \-un\fR with debug (\fB\-d\fR) output
enabled.
.PP
\fBsshp \-f hosts.txt \-m 1 \-g command\-to\-run\fR
.IP
Run with \fB\-g\fR (\fBgroup mode\fR) to group the output by hostname as it
comes in.  Setting \fB\-m\fR to \fB1\fR effectively turns \fBsshp\fR into an
\fBssh\fR serializer.
.PP
\fBsshp \-f hosts.txt \-j hostname\fR
.IP
Run with \fB\-j\fR (\fBjoin mode\fR) to group hosts that produce identical
output.
.SH EXIT STATUS
.TP
\fB0\fR
All child processes exited successfully.
.TP
\fB1\fR
One or more child processes exited with a non\-zero status.
.TP
\fB2\fR
Incorrect usage, such as an unknown option or invalid hosts file.
.TP
\fB3\fR
A system or internal program failure prevented \fBsshp\fR from running.
.TP
\fB4\fR
\fBsshp\fR exited after receiving \fBSIGTERM\fR or \fBSIGINT\fR\&.
.SH SIGNALS

\fBSIGUSR1\fR
.IP
Send a \fBSIGUSR1\fR signal to \fBsshp\fR to print a status message to stdout.
.PP
\fBSIGINT\fR, \fBSIGTERM\fR
.IP
Terminate running child processes and exit with status \fB4\fR\&.
.SH BUGS

\[la]https://github.com/bahamas10/sshp/issues\[ra]
.SH AUTHOR

Dave Eddy (\fBbahamas10\fR) <dave@daveeddy.com> (https://www.daveeddy.com)
.SH SEE ALSO

.BR ssh (1)
.PP
.BR ssh_config (5)
.SH LICENSE

MIT License
