#!/usr/bin/env bash
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: May 21, 2021
# License: MIT

. ./lib/helpers || exit 1

# loop arguments and run them
ret=0
for f in "$@"; do
	[[ ${f:0:1} == '/' ]] || f=./$f

	echo "${bld}running:$rst  $f"

	if ! "$f"; then
		ret=1
		echo
		echo "${red}error:  $f"
		echo
	fi

	echo
done

exit "$ret"
