#!/usr/bin/env bash
#
# very simple test for sshp just to verify some basic behavior
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 14, 2021
# License: MIT

. ./lib/helpers || exit 1

mkdir -p tmp
tmp=./tmp/output.$$

cleanup() {
	rm -f "$tmp"
}
trap cleanup EXIT

singlehost='./assets/hosts/single-host.txt'

# check all 3 modes, a good command should yield an exit code of 0
< "$singlehost" verify-cmd 0 sshp -x ./assets/cmd/true arg
< "$singlehost" verify-cmd 0 sshp -x ./assets/cmd/true -j arg
< "$singlehost" verify-cmd 0 sshp -x ./assets/cmd/true -g arg

# a bad command should be an exit code of 1
< "$singlehost" verify-cmd 1 sshp -x ./assets/cmd/false arg
< "$singlehost" verify-cmd 1 sshp -x ./assets/cmd/false -j arg
< "$singlehost" verify-cmd 1 sshp -x ./assets/cmd/false -g arg

# ensure that the output is "hello" if -a is specified
cmd=(sshp -x ./assets/cmd/hello -a arg)
output=$("${cmd[@]}" < "$singlehost")
code=$?

verify-equal 0 "$code" "${cmd[*]} code"
verify-equal 'hello' "$output" "${cmd[*]} stdout"

# ensure output larger than a pipe buffer is not truncated
# https://github.com/bahamas10/sshp/issues/17
cmd=(sshp -x ./assets/cmd/large-output -a arg)
"${cmd[@]}" < "$singlehost" > "$tmp"
code=$?
lines=$(awk 'END { print NR }' "$tmp")

verify-equal 0 "$code" "${cmd[*]} code"
verify-equal 200000 "$lines" "${cmd[*]} output lines"

# a child killed by a signal should be an exit code of 1
# https://github.com/bahamas10/sshp/issues/19
cmd=(sshp -x ./assets/cmd/sigterm -e arg)
"${cmd[@]}" < "$singlehost" > "$tmp"
code=$?

verify-equal 1 "$code" "${cmd[*]} code"
verify-cmd 0 grep -q 'exited: 143 ' "$tmp"

# a failed exec must not flush a copy of the parent's buffered output
cmd=(sshp -d -x ./assets/cmd/does-not-exist -a arg)
"${cmd[@]}" < "$singlehost" > "$tmp" 2>&1
code=$?
debug_headers=$(grep -c '^\[sshp\] hosts (1):' "$tmp")
exec_errors=$(grep -c '^sshp: exec:' "$tmp")

verify-equal 1 "$code" "${cmd[*]} code"
verify-equal 1 "$debug_headers" "${cmd[*]} debug header count"
verify-equal 1 "$exec_errors" "${cmd[*]} exec error count"

exit 0
