#!/usr/bin/env bash
#
# helper bash functions and variables for sshp tests
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: May 24, 2021
# License: MIT

# load some colors
[[ -t 1 ]] || tput() { true; }
red=$(tput setaf 1)
grn=$(tput setaf 2)
bld=$(tput bold)
rst=$(tput sgr0)
unset -f tput

#
# print a message to stderr and exit with failure
fatal() {
	echo "$@" >&2
	exit 1
}

#
# sshp wrapper to call the compiled version
sshp() {
	"${SSHP:-../sshp}" "$@"
}

#
# Verify that a command runs and exits with the expected code.
#
# Usage: verify <code> <cmd> [args ...]
#
# Example:
#
# verify 0 true
# verify 5 sh -c 'exit 5'
verify() {
	local code
	local want=$1
	local output

	shift

	echo -n "$bld$*$rst  exits $want ... "
	output=$("$@" 2>&1)
	code=$?

	if ((code == want)); then
		echo "${grn}ok$rst"
	else
		echo "${red}failed!$rst"
		echo '- program output -'
		echo "$output"
		exit 1
	fi
}
